const SET_TEMP = 'form/SET_TEMP'
const SET_TEST = 'form/SET_TEST'
const SET_CONTACT = 'form/SET_CONTACT'
const SET_PERSONNEL = 'form/SET_PERSONNEL'
const SET_SYMPTOMS = 'form/SET_SYMPTOMS'

export { SET_TEMP, SET_TEST, SET_CONTACT, SET_PERSONNEL, SET_SYMPTOMS }
