const SET_CATEGORIES = 'venue/SET_CATEGORIES'
const SET_TAB = 'venue/SET_TAB'
const SET_CHECKIN = 'venue/SET_CHECKIN'
const SET_VENUE = 'venue/SET_VENUE'

export { SET_CATEGORIES, SET_TAB, SET_CHECKIN, SET_VENUE }
